apiVersion: v1
kind: ServiceAccount
metadata:
  name: accounts-db
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: accounts-db
  labels:
    app: accounts-db
    tier: db
spec:
  serviceName: "accounts-db"
  replicas: 1
  selector:
    matchLabels:
      app: accounts-db
      tier: db
  template:
    metadata:
      labels:
        app: accounts-db
        tier: db
    spec:
      serviceAccountName: accounts-db
      containers:
      - name: accounts-db
        image: gcr.io/bank-of-anthos-ci/accounts-db:v0.5.4
        envFrom:
          - configMapRef:
              name: environment-config
          - configMapRef:
              name: accounts-db-config
          - configMapRef:
              name: demo-data-config
        ports:
          - containerPort: 5432
            name: postgredb
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 512Mi
        volumeMounts:
        - name: postgresdb
          mountPath: /var/lib/postgresql/data
          subPath: postgres
      volumes:
      - name: postgresdb
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-db
  labels:
    app: accounts-db
    tier: db
spec:
  ports:
    - port: 5432
      name: tcp
      targetPort: 5432
      protocol: TCP
  selector:
    app: accounts-db
    tier: db
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: accounts-db-config
  labels:
    app: accounts-db
data:
  POSTGRES_DB: accounts-db
  POSTGRES_USER: accounts-admin
  POSTGRES_PASSWORD: accounts-pwd
  ACCOUNTS_DB_URI: postgresql://accounts-admin:accounts-pwd@accounts-db:5432/accounts-db